version: '2.4'
services:
  php:
    build: ./docker/dockerfiles/php
    volumes:
      - ./:/var/www/html # also in nginx
      - ./docker/etc/php/dev:/usr/local/etc/php/custom-postconf.d
      - ./docker/local-data/composer:/root/.composer
    restart: on-failure
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d:/usr/local/etc/php/custom-postconf.d"
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9000 var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=docker-yii2-advanced"

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/html # from php
      - ./docker/etc/nginx:/etc/nginx/conf.d
      - ./docker/local-data/nginx-logs:/var/log/nginx
    restart: on-failure